[package]
name = "pse"
description = "a simple cli tool for interacting with google pubsub emulator"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.5.47", features = ["derive", "env"] }
confy = "2.0.0"
gcloud-gax = "1.3.2"
gcloud-pubsub = { version = "1.6.0" }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.47.1", features = ["rt", "macros"] }


[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
debug = false
overflow-checks = false
